[package]
name = "bbee"
version = "0.1.0"
authors = ["LeoDog896 <LeoDog896@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.13"
walkdir = "2"
toml = "0.4.2"