[info]
name = "GSON"
main = "Gson"
group = "example.gson"

dependencies = [
	# BBee supports maven dependencies and will automatically check mavenCentral
	{ "com.google.code.gson:gson" = { version = "2.8.7", shade = "all" } }
]