[info]
name = "GSON"

# no need to add repositories, mavenCentral is default.

# By default, dependencies are not shaded and only exist during compile time.
[dependencies]

"com.google.code.gson:gson" = { version = "2.8.7", type = "shade" }